language: scala

jdk:
  - openjdk8

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    # stage="test" if no stage is specified
    - env: TEST="build"
      script: sbt ";headerCheck; + compile; + test"
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.cache

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

